build: false


environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_USERNAME: "fbergmann"
    CONAN_LOGIN_USERNAME: "fbergmann"
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/fbergmann/conan"
    CONAN_BUILD_POLICY: "missing"

    matrix:
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86_64@sjlj@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86@sjlj@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "5@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "6@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "7@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "8@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py

